<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" aria-current="page"> 
<span class="menu-text">Analysis</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#exploratory-analysis-of-the-whr-dataset" id="toc-exploratory-analysis-of-the-whr-dataset" class="nav-link" data-scroll-target="#exploratory-analysis-of-the-whr-dataset"><span class="header-section-number">2</span> Exploratory Analysis of the WHR Dataset</a></li>
  <li><a href="#mixed-model-specification-choice-of-fixed-and-random-effects" id="toc-mixed-model-specification-choice-of-fixed-and-random-effects" class="nav-link" data-scroll-target="#mixed-model-specification-choice-of-fixed-and-random-effects"><span class="header-section-number">3</span> Mixed Model Specification: Choice of Fixed and Random Effects</a></li>
  <li><a href="#estimation-and-interpretation-of-the-final-model" id="toc-estimation-and-interpretation-of-the-final-model" class="nav-link" data-scroll-target="#estimation-and-interpretation-of-the-final-model"><span class="header-section-number">4</span> Estimation and Interpretation of the Final Model</a></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics"><span class="header-section-number">5</span> Model Diagnostics</a></li>
  <li><a href="#model-performance-assessment" id="toc-model-performance-assessment" class="nav-link" data-scroll-target="#model-performance-assessment"><span class="header-section-number">6</span> Model Performance Assessment</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>Linear Mixed Models (LMM) are statistical tools suited for analyzing grouped or longitudinal data (Pinheiro &amp; Bates, 2000). They incorporate two types of effects: <strong>fixed effects</strong>, which are common to all observations, and <strong>random effects</strong>, which are specific to groups or individuals. This structure allows LMMs to capture between-group heterogeneity, which is often ignored by standard linear regression models (Ordinary Least Squares, OLS).</p>
<p>Despite their ability to account for both hierarchical and temporal dependencies in data, LMMs remain underused in many fields. Analyses still frequently rely on pooled OLS regressions, which overlook country-specific dynamics and longitudinal evolution. This is the case in the World Happiness Report (Helliwell et al.), where OLS models are applied to pooled data without modeling country-specific intercepts or trends, potentially biasing the estimation of happiness-related factors (Ferrer-i-Carbonell &amp; Frijters, 2004).</p>
<p>The main objective of this study is to empirically demonstrate how LMMs better account for cross-country heterogeneity and temporal structure in longitudinal data.</p>
</section>
<section id="exploratory-analysis-of-the-whr-dataset" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="exploratory-analysis-of-the-whr-dataset"><span class="header-section-number">2</span> Exploratory Analysis of the WHR Dataset</h2>
<p>The dataset includes <strong>1,363 observations</strong> covering <strong>168 countries</strong> over the period <strong>2015–2023</strong>. Each row represents the average happiness score for a specific country in a given year, along with six explanatory variables:</p>
<ul>
<li>GDP per capita</li>
<li>Healthy life expectancy<br>
</li>
<li>Social support<br>
</li>
<li>Freedom to make life choices<br>
</li>
<li>Generosity<br>
</li>
<li>Perceptions of corruption</li>
</ul>
<p>In addition, countries are grouped into major global regions (e.g., Western Europe, East Asia, Sub-Saharan Africa). The goal is to construct a Linear Mixed Model that explains the happiness score based on these variables, while accounting for the hierarchical structure of the data: repeated measures within countries, and countries nested within regions.</p>
<div class="note-box">
<p><strong>🧾 About the Response Variable</strong></p>
<p>The happiness score used in the World Happiness Report originates from the Gallup World Poll. It is based on a single survey question:</p>
<blockquote class="blockquote">
<p>“<strong>On a scale from 0 to 10, where 0 represents the worst possible life and 10 the best possible life, how would you rate your life currently?</strong>”</p>
</blockquote>
<p>The score assigned to each country is the average of the individual responses collected. Unlike other indexes, the happiness score is not a composite index: the six explanatory variables (GDP, social support, etc.) are used only to explain the variation in happiness across countries. They do not contribute directly to the score’s construction.</p>
</div>
<section id="data-preview" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="data-preview"><span class="header-section-number">2.1</span> Data preview</h3>
<p>We start with a descriptive overview to understand how happiness varies over time, across countries and regions. Below is a preview of the raw dataset (first 5 rows):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>whr_data <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Table 1 – First 5 observations of the WHR dataset (2015–2023)"</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1 – First 5 observations of the WHR dataset (2015–2023)</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 14%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">pays</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">score_bonheur</th>
<th style="text-align: right;">pib_par_habitant</th>
<th style="text-align: right;">soutien_social</th>
<th style="text-align: right;">esperance_vie_saine</th>
<th style="text-align: right;">liberte_choix_vie</th>
<th style="text-align: right;">generosite</th>
<th style="text-align: right;">perception_corruption</th>
<th style="text-align: right;">annee</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: left;">Western Europe</td>
<td style="text-align: right;">7.587</td>
<td style="text-align: right;">1.397</td>
<td style="text-align: right;">1.350</td>
<td style="text-align: right;">0.941</td>
<td style="text-align: right;">0.666</td>
<td style="text-align: right;">0.297</td>
<td style="text-align: right;">0.420</td>
<td style="text-align: right;">2015</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iceland</td>
<td style="text-align: left;">Western Europe</td>
<td style="text-align: right;">7.561</td>
<td style="text-align: right;">1.302</td>
<td style="text-align: right;">1.402</td>
<td style="text-align: right;">0.948</td>
<td style="text-align: right;">0.629</td>
<td style="text-align: right;">0.436</td>
<td style="text-align: right;">0.141</td>
<td style="text-align: right;">2015</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Denmark</td>
<td style="text-align: left;">Western Europe</td>
<td style="text-align: right;">7.527</td>
<td style="text-align: right;">1.325</td>
<td style="text-align: right;">1.361</td>
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">0.649</td>
<td style="text-align: right;">0.341</td>
<td style="text-align: right;">0.484</td>
<td style="text-align: right;">2015</td>
</tr>
<tr class="even">
<td style="text-align: left;">Norway</td>
<td style="text-align: left;">Western Europe</td>
<td style="text-align: right;">7.522</td>
<td style="text-align: right;">1.459</td>
<td style="text-align: right;">1.331</td>
<td style="text-align: right;">0.885</td>
<td style="text-align: right;">0.670</td>
<td style="text-align: right;">0.347</td>
<td style="text-align: right;">0.365</td>
<td style="text-align: right;">2015</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Canada</td>
<td style="text-align: left;">North America and ANZ</td>
<td style="text-align: right;">7.427</td>
<td style="text-align: right;">1.326</td>
<td style="text-align: right;">1.323</td>
<td style="text-align: right;">0.906</td>
<td style="text-align: right;">0.633</td>
<td style="text-align: right;">0.458</td>
<td style="text-align: right;">0.330</td>
<td style="text-align: right;">2015</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
</section>
<section id="temporal-variation-in-global-happiness" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="temporal-variation-in-global-happiness"><span class="header-section-number">2.2</span> Temporal variation in global happiness</h3>
<p>We begin by examining the evolution of the global average happiness score between 2015 and 2023. This helps determine whether global happiness remained stable or changed over time. Figure 1 shows the average score for each year.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate yearly mean happiness score</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mean_by_year <span class="ot">&lt;-</span> whr_data <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(annee) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">moyenne_bonheur =</span> <span class="fu">mean</span>(score_bonheur, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot average score by year</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mean_by_year, <span class="fu">aes</span>(<span class="at">x =</span> annee, <span class="at">y =</span> moyenne_bonheur)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average happiness score"</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 1 – Global average happiness score by year</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<p>Between 2015 and 2018, the global score remained relatively stable around 5.35–5.38. From 2019 onward, we observe a gradual increase, peaking at 5.56 in 2022, before slightly declining in 2023. This trend suggests a global temporal effect. To account for this dynamic in the model, we will include a fixed effect for year. A random slope by country may also be considered if the trend differs across countries.</p>
</section>
<section id="variation-across-countries-and-regions" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="variation-across-countries-and-regions"><span class="header-section-number">2.3</span> Variation across countries and regions</h3>
<p>We continue the analysis by examining differences in happiness scores between countries, taking into account their regional affiliation. To do this, we plot the trajectories of happiness scores over time for each country, grouped by major geographical region.</p>
<p>Each line represents the evolution of a single country between 2015 and 2023. This visualization allows us to assess whether countries within the same region follow similar trends or not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(whr_data, <span class="fu">aes</span>(<span class="at">x =</span> annee, <span class="at">y =</span> score_bonheur, <span class="at">group =</span> pays)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> region) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Happiness score"</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 2 – Happiness score trajectories by country and region</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<p>Figure 2 shows that happiness levels vary across countries and regions. Some regions, such as Western Europe and North America and ANZ, have high and relatively stable scores across countries. Others, like Sub-Saharan Africa and South Asia, exhibit lower scores and greater dispersion.</p>
<p>In certain regions—such as Southeast Asia—country curves are close to one another, suggesting a shared trend. In contrast, Middle East and North Africa shows greater variability between countries.</p>
<p>We also observe that some countries lack data for every year, introducing imbalance in the longitudinal structure.</p>
<p>These results highlight both cross-country differences and inter-regional disparities. For the upcoming modeling, it may be appropriate to include a random effect by country to account for country-specific characteristics. The region can also be included, either as a fixed effect (if we wish to compare regions explicitly) or as a random effect (if treated as a sample of possible geographic clusters).</p>
</section>
</section>
<section id="mixed-model-specification-choice-of-fixed-and-random-effects" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="mixed-model-specification-choice-of-fixed-and-random-effects"><span class="header-section-number">3</span> Mixed Model Specification: Choice of Fixed and Random Effects</h2>
<p>The exploratory analysis revealed three main sources of variation: persistent differences between countries, different temporal dynamics across countries, and disparities between regions. To address these, we progressively test three random effects:</p>
<ul>
<li>A random intercept by country, to model differences in average happiness levels across countries<br>
</li>
<li>A random slope for year by country, to capture country-specific temporal trends<br>
</li>
<li>A random intercept by region, to account for similarities between countries within the same region</li>
</ul>
<section id="random-intercept-by-country" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="random-intercept-by-country"><span class="header-section-number">3.1</span> Random Intercept by Country</h3>
<p>We start by introducing a random intercept for each country. This allows each country to have its own baseline happiness level, centered around a global intercept <code>β0</code> shared across countries.</p>
<p>The model is written as:</p>
<p><code>score_bonheur = β0 + β1 · annee_c + α0_pays + ε</code></p>
<p>Where:</p>
<ul>
<li><code>β0</code>: global intercept (interpreted as the average happiness score in 2019)<br>
</li>
<li><code>β1</code>: fixed effect for the centered year<br>
</li>
<li><code>α0_pays</code>: random intercept specific to each country<br>
</li>
<li><code>ε</code>: residual error</li>
</ul>
<p>This effect is essential for modeling the within-country correlation over time and will be kept in all subsequent models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Centering the year variable</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>whr_data<span class="sc">$</span>annee_c <span class="ot">&lt;-</span> <span class="fu">scale</span>(whr_data<span class="sc">$</span>annee, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Model with random intercept by country</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>mod_intercept_pays <span class="ot">&lt;-</span> <span class="fu">lmer</span>(score_bonheur <span class="sc">~</span> annee_c <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> pays),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> whr_data, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="note-box">
<p><strong>📝 Note on Centering the Year Variable</strong></p>
<p>To improve model estimation and interpretation, we center the <code>annee</code> variable around its mean:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>whr_data<span class="sc">$</span>annee_c <span class="ot">&lt;-</span> <span class="fu">scale</span>(whr_data<span class="sc">$</span>annee, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This means that a value of 0 for <code>annee_c</code> corresponds to the average year in the dataset, i.e., 2019. As a result, the intercept <code>β0</code> can be interpreted as the average happiness score for 2019.</p>
<p>Centering also improves numerical stability, especially when including random slopes. This practice is recommended in the <a href="https://cran.r-project.org/web/packages/lme4/lme4.pdf">lme4 documentation</a>.</p>
</div>
</section>
<section id="random-slope-for-year-by-country" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="random-slope-for-year-by-country"><span class="header-section-number">3.2</span> Random Slope for Year by Country</h3>
<p>We next test whether the evolution of happiness over time varies by country. To do this, we add a random slope for year by country, in addition to the random intercept.</p>
<p>The model becomes:</p>
<p><code>score_bonheur = β0 + β1 · annee_c + α0_pays + α1_pays · annee_c + ε</code></p>
<p>Where <code>α1_pays</code> allows each country to have its own time trend.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model with random intercept and slope by country</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mod_pente_pays <span class="ot">&lt;-</span> <span class="fu">lmer</span>(score_bonheur <span class="sc">~</span> annee_c <span class="sc">+</span> (annee_c <span class="sc">|</span> pays),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> whr_data, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Likelihood ratio test vs. the simpler model</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_intercept_pays, mod_pente_pays) <span class="sc">%&gt;%</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Table 2 – Likelihood ratio test between the two models"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2 – Likelihood ratio test between the two models</caption>
<colgroup>
<col style="width: 24%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">npar</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">Chisq</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod_intercept_pays</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1417.47</td>
<td style="text-align: right;">1438.34</td>
<td style="text-align: right;">-704.73</td>
<td style="text-align: right;">1409.47</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod_pente_pays</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">700.17</td>
<td style="text-align: right;">731.48</td>
<td style="text-align: right;">-344.09</td>
<td style="text-align: right;">688.17</td>
<td style="text-align: right;">721.29</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<p>The likelihood ratio test confirms that the model with random slopes significantly improves model fit compared to the simpler model with only a random intercept (Chisq = 721.29, df = 2). The two degrees of freedom correspond to the added variance of the slope and its covariance with the intercept. This confirms that year effects vary across countries, justifying the inclusion of a random slope.</p>
</section>
<section id="modeling-the-region-variable" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="modeling-the-region-variable"><span class="header-section-number">3.3</span> Modeling the Region Variable</h3>
<p>Countries in the dataset are grouped into major geographic regions (Western Europe, East Asia, Sub-Saharan Africa, etc.). The exploratory analysis showed that some regions tend to have higher or lower average happiness scores.</p>
<p>In the mixed model, the <code>region</code> variable can be treated either as a fixed effect or as a random effect.</p>
<ul>
<li><p>Fixed effect: Each region is explicitly estimated via a separate coefficient, allowing direct comparison. This approach is appropriate when the number of regions is small and their effects are of direct interest.</p></li>
<li><p>Random effect: The region is treated as an additional source of variability, assumed to be drawn from a broader population of possible regions. This is useful when the goal is to capture variance rather than interpret region-specific effects.</p></li>
</ul>
<p>In our case, regions are few, predefined, and of substantive interest. We therefore choose to model <code>region</code> as a fixed effect. This will allow us to interpret the differences in mean happiness across major world regions more clearly.</p>
</section>
<section id="selection-of-explanatory-fixed-effects" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="selection-of-explanatory-fixed-effects"><span class="header-section-number">3.4</span> Selection of Explanatory Fixed Effects</h3>
<p>The WHR dataset provides several quantitative variables designed to explain reported happiness scores. These include:</p>
<ul>
<li>pib_par_habitant: Gross Domestic Product (GDP) per capita, reflecting the average economic wealth and overall performance of a country.<br>
</li>
<li>soutien_social: Perceived social support during difficult times. Based on the question: Do you have someone (friends or family) to count on in times of trouble?<br>
</li>
<li>esperance_vie_saine: Healthy life expectancy, combining longevity and physical/mental health. Mental health is a key driver of subjective well-being.<br>
</li>
<li>liberte_choix_vie: Satisfaction with the freedom to choose what one does with one’s life. Also relates to fundamental human rights such as freedom of speech, education, work, and opinion.<br>
</li>
<li>generosite: Altruistic behavior, measured by recent donations (e.g., during the past month). A proxy for community engagement and social connection.<br>
</li>
<li>perception_corruption: Perceived corruption in both public institutions and private businesses, derived from questions about trust in government and the corporate world.</li>
</ul>
<p>These variables are part of the official methodology of the World Happiness Report and are theoretically considered determinants of happiness. Given their relevance, all six variables are retained in the model as fixed effects, without prior variable selection. This ensures methodological coherence with the WHR and enables a clear interpretation of each variable’s contribution to happiness levels.</p>
</section>
<section id="final-mixed-model-specification" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="final-mixed-model-specification"><span class="header-section-number">3.5</span> Final Mixed Model Specification</h3>
<p>The final Linear Mixed Model includes:</p>
<ul>
<li>Fixed effects:
<ul>
<li>Centered year (<code>annee_c</code>)<br>
</li>
<li>Region<br>
</li>
<li>The six explanatory variables listed above</li>
</ul></li>
<li>Random effects:
<ul>
<li>A random intercept and a random slope for year, both at the country level</li>
</ul></li>
</ul>
<p>The model is written as:</p>
<p><code>score_bonheur = β0 + β1 · annee_c + β2 · X2 + ... + β7 · X7 + γ_r + α0_pays + α1_pays · annee_c + ε</code></p>
<p>Where:</p>
<ul>
<li><code>β0</code> is the global intercept<br>
</li>
<li><code>β1</code> to <code>β7</code> are coefficients for the quantitative predictors (<code>pib</code>, <code>soutien</code>, <code>vie_saine</code>, etc.)<br>
</li>
<li><code>γ_r</code> is the fixed effect for region <code>r</code><br>
</li>
<li><code>α0_pays</code> is the country-specific random intercept<br>
</li>
<li><code>α1_pays</code> is the country-specific random slope on centered year<br>
</li>
<li><code>ε</code> is the residual error term</li>
</ul>
</section>
</section>
<section id="estimation-and-interpretation-of-the-final-model" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="estimation-and-interpretation-of-the-final-model"><span class="header-section-number">4</span> Estimation and Interpretation of the Final Model</h2>
<p>We now estimate the selected Linear Mixed Model using the <code>lmer()</code> function, including the previously identified fixed effects, along with a random intercept and a random slope on year at the country level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the final model</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>mod_final <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  score_bonheur <span class="sc">~</span> annee_c <span class="sc">+</span> region <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    pib_par_habitant <span class="sc">+</span> soutien_social <span class="sc">+</span> esperance_vie_saine <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    liberte_choix_vie <span class="sc">+</span> generosite <span class="sc">+</span> perception_corruption <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    (annee_c <span class="sc">|</span> pays),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> whr_data</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tables 3a and 3b present the fitted model results, including both random-effect variances and fixed-effect estimates. Fixed-effect p-values were computed using the Satterthwaite approximation via the <strong><code>lmerTest</code></strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Table 3a: Fixed effects</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>fixed_effects <span class="ot">&lt;-</span> <span class="fu">tidy</span>(mod_final, <span class="at">effects =</span> <span class="st">"fixed"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  fixed_effects,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Table 3a – Fixed Effects from the Linear Mixed Model"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3a – Fixed Effects from the Linear Mixed Model</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 43%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">effect</th>
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">4.908</td>
<td style="text-align: right;">0.159</td>
<td style="text-align: right;">30.800</td>
<td style="text-align: right;">358.425</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">annee_c</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">1.581</td>
<td style="text-align: right;">225.449</td>
<td style="text-align: right;">0.115</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionCommonwealth of Independent States</td>
<td style="text-align: right;">-0.165</td>
<td style="text-align: right;">0.290</td>
<td style="text-align: right;">-0.571</td>
<td style="text-align: right;">138.169</td>
<td style="text-align: right;">0.569</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionEast Asia</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">0.268</td>
<td style="text-align: right;">-0.013</td>
<td style="text-align: right;">136.443</td>
<td style="text-align: right;">0.990</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionLatin America and Caribbean</td>
<td style="text-align: right;">0.326</td>
<td style="text-align: right;">0.170</td>
<td style="text-align: right;">1.921</td>
<td style="text-align: right;">140.150</td>
<td style="text-align: right;">0.057</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionMiddle East and North Africa</td>
<td style="text-align: right;">-0.291</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">-1.647</td>
<td style="text-align: right;">141.340</td>
<td style="text-align: right;">0.102</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionNorth America and ANZ</td>
<td style="text-align: right;">1.145</td>
<td style="text-align: right;">0.323</td>
<td style="text-align: right;">3.544</td>
<td style="text-align: right;">144.992</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionSouth Asia</td>
<td style="text-align: right;">-1.072</td>
<td style="text-align: right;">0.242</td>
<td style="text-align: right;">-4.422</td>
<td style="text-align: right;">142.726</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionSoutheast Asia</td>
<td style="text-align: right;">-0.514</td>
<td style="text-align: right;">0.233</td>
<td style="text-align: right;">-2.210</td>
<td style="text-align: right;">144.070</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionSub-Saharan Africa</td>
<td style="text-align: right;">-1.224</td>
<td style="text-align: right;">0.155</td>
<td style="text-align: right;">-7.878</td>
<td style="text-align: right;">166.216</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">regionWestern Europe</td>
<td style="text-align: right;">0.881</td>
<td style="text-align: right;">0.180</td>
<td style="text-align: right;">4.893</td>
<td style="text-align: right;">151.843</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">pib_par_habitant</td>
<td style="text-align: right;">-0.014</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">-0.310</td>
<td style="text-align: right;">1220.100</td>
<td style="text-align: right;">0.757</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">soutien_social</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: right;">1.303</td>
<td style="text-align: right;">1100.111</td>
<td style="text-align: right;">0.193</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">esperance_vie_saine</td>
<td style="text-align: right;">0.289</td>
<td style="text-align: right;">0.064</td>
<td style="text-align: right;">4.507</td>
<td style="text-align: right;">1177.976</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">liberte_choix_vie</td>
<td style="text-align: right;">0.878</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">7.273</td>
<td style="text-align: right;">1326.759</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">generosite</td>
<td style="text-align: right;">0.535</td>
<td style="text-align: right;">0.182</td>
<td style="text-align: right;">2.934</td>
<td style="text-align: right;">1306.492</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">perception_corruption</td>
<td style="text-align: right;">0.491</td>
<td style="text-align: right;">0.224</td>
<td style="text-align: right;">2.192</td>
<td style="text-align: right;">1305.237</td>
<td style="text-align: right;">0.029</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Table 3b: Random effects (variances, covariances, residuals)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>random_effects <span class="ot">&lt;-</span> <span class="fu">tidy</span>(mod_final, <span class="at">effects =</span> <span class="st">"ran_pars"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  random_effects,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Table 3b – Random Effects from the Linear Mixed Model"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3b – Random Effects from the Linear Mixed Model</caption>
<thead>
<tr class="header">
<th style="text-align: left;">effect</th>
<th style="text-align: left;">group</th>
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">pays</td>
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: right;">0.584</td>
</tr>
<tr class="even">
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">pays</td>
<td style="text-align: left;">cor__(Intercept).annee_c</td>
<td style="text-align: right;">0.058</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">pays</td>
<td style="text-align: left;">sd__annee_c</td>
<td style="text-align: right;">0.085</td>
</tr>
<tr class="even">
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">Residual</td>
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: right;">0.190</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<section id="fixed-effects" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="fixed-effects"><span class="header-section-number">4.1</span> Fixed Effects</h3>
<p>The fixed effects coefficients estimate the average impact of each explanatory variable on happiness, all else equal.</p>
<ul>
<li>The fixed intercept is estimated at 4.908 (p &lt; 0.001). It represents the average happiness score in 2019 (the centered year) for a country in the reference region, with all quantitative variables set to zero.</li>
<li>A one-unit increase in freedom to make life choices (<code>liberte_choix_vie</code>) is associated with a +0.878 increase in happiness score (p &lt; 0.001).</li>
<li>Healthy life expectancy (<code>esperance_vie_saine</code>) has a positive and significant effect: +0.289 (p &lt; 0.001).</li>
<li>Generosity (<code>generosite</code>) and perceived corruption (<code>perception_corruption</code>) also show positive associations, estimated at +0.535 (p = 0.003) and +0.491 (p = 0.029), respectively.</li>
<li>In contrast, GDP per capita (<code>pib_par_habitant</code>), social support (<code>soutien_social</code>), and centered year (<code>annee_c</code>) do not exhibit significant effects in this model.</li>
</ul>
<section id="regional-fixed-effects" class="level4" data-number="4.1.1">
<h4 data-number="4.1.1" class="anchored" data-anchor-id="regional-fixed-effects"><span class="header-section-number">4.1.1</span> Regional Fixed Effects</h4>
<p>The reference category for region is Central and Eastern Europe. Compared to this baseline:</p>
<ul>
<li>Western Europe: +0.881 (p &lt; 0.001)<br>
</li>
<li>North America and ANZ: +1.145 (p = 0.001)<br>
</li>
<li>South Asia: −1.072 (p &lt; 0.001)<br>
</li>
<li>Sub-Saharan Africa: −1.224 (p &lt; 0.001)<br>
</li>
<li>Other regions do not significantly differ from the reference region.</li>
</ul>
</section>
</section>
<section id="random-effects" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="random-effects"><span class="header-section-number">4.2</span> Random Effects</h3>
<p>The model includes both a random intercept and a random slope on year for each country, allowing the model to capture country-specific variations.</p>
<ul>
<li>The random intercept allows each country to have its own average happiness level around the fixed intercept (4.908). The estimated variance is 0.341 (0.584²), indicating notable between-country heterogeneity.</li>
<li>The random slope lets each country follow its own trend over time. Its variance is 0.007 (0.085²), showing some differences in how happiness evolves across countries.</li>
<li>The correlation between intercept and slope is close to zero (0.06), suggesting no systematic link between a country’s baseline happiness and the direction of its temporal trend.</li>
<li>The residual variance is 0.036 (0.190²), representing the share of happiness variation not explained by the model.</li>
</ul>
</section>
</section>
<section id="model-diagnostics" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="model-diagnostics"><span class="header-section-number">5</span> Model Diagnostics</h2>
<p>We now evaluate the assumptions underlying the Linear Mixed Model by analyzing the random effects, residuals, and their independence.</p>
<section id="normality-of-random-effects" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="normality-of-random-effects"><span class="header-section-number">5.1</span> Normality of Random Effects</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load lattice package</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract random effects</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>rr <span class="ot">&lt;-</span> <span class="fu">ranef</span>(mod_final)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># QQ-plot to assess normality of random effects</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">qqmath</span>(rr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$pays</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 3 – QQ-plot of random effects (intercept and slope for annee_c)</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<p>Figure 3 shows that the points generally follow the diagonal. Despite some deviations at the extremes, the assumption of normality for the random effects is not seriously violated.</p>
</section>
<section id="normality-of-residuals" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="normality-of-residuals"><span class="header-section-number">5.2</span> Normality of Residuals</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># QQ-plot of Pearson residuals</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqmath</span>(mod_final, <span class="at">form =</span> <span class="sc">~</span><span class="fu">resid</span>(., <span class="at">type =</span> <span class="st">"pearson"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 4 – QQ-plot of Pearson residuals</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<p>Figure 4 suggests that residuals roughly align with the diagonal, although several points deviate, especially in the tails. This indicates a mild departure from the normality assumption.</p>
</section>
<section id="independence-between-random-effects-and-residuals" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="independence-between-random-effects-and-residuals"><span class="header-section-number">5.3</span> Independence Between Random Effects and Residuals</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean of residuals by country</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ranefs <span class="ot">&lt;-</span> <span class="fu">ranef</span>(mod_final, <span class="at">condVar =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>pays</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>res_mean <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="fu">residuals</span>(mod_final), whr_data<span class="sc">$</span>pays, mean)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot: Random intercept vs mean residuals</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ranefs[,<span class="st">"(Intercept)"</span>], res_mean,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Random Intercept"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Mean Residuals"</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Relationship Between Random Intercept and Mean Residuals"</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">v =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 5 – Relationship between random intercept and average residuals by country</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<p>Figure 5 shows a positive relationship between the estimated random intercept for each country and its average residual. This pattern suggests a potential violation of the assumption of independence between random effects and residuals.</p>
</section>
</section>
<section id="model-performance-assessment" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="model-performance-assessment"><span class="header-section-number">6</span> Model Performance Assessment</h2>
<p>To evaluate the performance of the model, we compute coefficients of determination (R²) specifically adapted to linear mixed models. Unlike classical linear regression, several definitions of R² exist for mixed-effects models. The <strong><code>performance</code></strong> package provides two widely used measures introduced by <a href="https://doi.org/10.1111/j.2041-210X.2012.00261.x">Nakagawa &amp; Schielzeth (2013)</a>:</p>
<ul>
<li>Marginal R² (R²ₘ): proportion of variance in the happiness score explained only by the fixed effects (e.g., GDP, freedom, life expectancy).<br>
</li>
<li>Conditional R² (R²𝒄): proportion of variance explained by the entire model, including both fixed effects and random effects (e.g., between-country heterogeneity).</li>
</ul>
<p>Higher values of R² indicate that the model explains a greater share of the outcome variability.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute R² for the linear mixed model</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>r2_values <span class="ot">&lt;-</span> <span class="fu">r2</span>(mod_final)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  r2_values,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="kable_wrapper">
<caption>
Table 4 – Coefficient of determination
</caption>
<tbody>
<tr>
<td>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Conditional R2</td>
<td style="text-align: right;">0.97</td>
</tr>
</tbody>
</table>
</td>
<td>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Marginal R2</td>
<td style="text-align: right;">0.65</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>📎 <em>Source: Author’s computation based on WHR data (2015–2023)</em></p>
</blockquote>
<p>The marginal R² is 0.65, meaning that the fixed effects alone explain 65% of the variance in happiness scores.</p>
<p>The conditional R² reaches 0.97, indicating that the full model—including country-level random effects—accounts for 97% of the total variance.</p>
</section>
<section id="conclusion" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">7</span> Conclusion</h2>
<p>This study aimed to illustrate the use of Linear Mixed Models (LMM) with data from the World Happiness Report (WHR). These models allowed us to jointly model both cross-country differences and temporal evolution in happiness scores.</p>
<p>The results highlight that several factors have a significant effect on national happiness:<br>
- Freedom to make life choices (+0.878)<br>
- Healthy life expectancy (+0.289)<br>
- Generosity (+0.535)<br>
- Perception of corruption (+0.491)</p>
<p>Clear regional disparities are observed. Compared to the reference region (Central and Eastern Europe), we find:<br>
- Western Europe: +0.881<br>
- North America and ANZ: +1.145<br>
- Sub-Saharan Africa: −1.224<br>
- South Asia: −1.072</p>
<p>The model reveals substantial between-country heterogeneity, with a random intercept variance of 0.341. On the other hand, the random slope variance is lower (0.007), suggesting limited differences in the evolution of happiness over time. The correlation between initial levels and temporal trends is also weak (0.06).</p>
<p>Overall, the model fits the data well, with a conditional R² of 0.97, indicating that the combined fixed and random effects explain 97% of the variance in happiness scores.</p>
<p>However, implementing LMMs requires careful assumption checks. In this application, a dependence was observed between residuals and the random intercept, calling into question the assumption of independence. This suggests that the random structure may need revision, or that non-Gaussian mixed models could be more appropriate.</p>
<p>Possible extensions include:<br>
- Studying the impact of assumption violations on the estimates<br>
- Comparing alternative random structures<br>
- Exploring corrective approaches</p>
<p>These steps would help better understand how methodological choices influence the results obtained from hierarchical modeling.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2024 Cheikh LO</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>